language: node_js
node_js:
  - "6"
  - "5"
  - "4"
sudo: false
services:
  - mysql
env:
  - DB_USER=mp DB_PASS='mp'
before_script:
  - mysql -e 'create database mppg;'
  - mysql -e "create user 'mp'@'localhost' identified by 'mp';"
  - mysql -e "grant all privileges on * . * to 'mp'@'localhost';" -u root
  - mysql -e "flush privileges;" -u root
