adapter:
  build: .
  volumes:
   - .:/usr/src/app
  links:
   - mysql

mysql:
  image: mysql
  environment:
   - MYSQL_DATABASE=mppg
   - MYSQL_USER=mp
   - MYSQL_PASSWORD=mp
   - MYSQL_ROOT_PASSWORD=mppg
